create table clinica (
  clinica_id int not null generated by default as identity primary key,
  clinical_name varchar(64) not null,
  clinical_phone_number varchar(24) not null,
  clinical_address varchar(120) not null
);

create table clinical_services (
  clinical_services_id int not null generated by default as identity primary key,
  clinical_service_name varchar(24) not null,
  clinica_id int not null references clinica (clinica_id)
);

create table patient (
  patient_id int not null generated by default as identity primary key,
  patient_name varchar(24) not null,
  patient_phone_number varchar(24) not null,
  clinica_id int not null references clinica (clinica_id),
  clinical_services_id int not null references clinical_services (clinical_services_id)
);

create table clinica_analyzes (
  analysis_id int not null generated by default as identity primary key,
  analysis_text varchar(500) not null,
  clinica_id int not null references clinica (clinica_id),
  clinical_services_id int not null references clinical_services (clinical_services_id),
  patient_id int not null references patient (patient_id)
);